PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX schema: <https://schema.org/>

SELECT ?name (COUNT(DISTINCT ?sid) as ?count)
WHERE {
    ?sid schema:variableMeasured ?prop .
    ?prop schema:name ?name .
    FILTER regex(str(?name), "depth", "i")
}
GROUP BY ?name ORDER BY DESC(?count)
